# Generated by Django 5.0.6 on 2024-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupancy',
            name='rent_is_paid',
        ),
        migrations.AddField(
            model_name='occupancy',
            name='rent_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Overdue', max_length=8),
            preserve_default=False,
        ),
    ]
