# Generated by Django 5.0.6 on 2024-07-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_occupancy_rent_is_paid_occupancy_rent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='houses/photos')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.house')),
            ],
        ),
    ]
