# Generated by Django 5.0.6 on 2024-07-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
