# Generated by Django 5.0.6 on 2024-07-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rename_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.CharField(choices=[('Single', 'Single'), ('Bedsitter', 'Bedsitter'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom')], max_length=20),
        ),
    ]
