# Generated by Django 5.0.6 on 2024-07-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_house_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='bedrooms',
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('Single', 'Single'), ('Bedsitter', 'Bedsitter'), ('Studio', 'Studio'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom')], default='Studio', max_length=20),
            preserve_default=False,
        ),
    ]
