# Generated by Django 5.0.6 on 2024-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_remove_house_bedrooms_house_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('Single', 'Single'), ('Bedsitter', 'Bedsitter'), ('Studio', 'Studio'), ('One_Bedroom', 'One Bedroom'), ('Two_Bedroom', 'Two Bedroom')], max_length=20),
        ),
    ]
