# Generated by Django 5.0.6 on 2024-07-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_house_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='kitchen',
            new_name='cctv',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='washroom',
            new_name='garbage',
        ),
        migrations.AddField(
            model_name='house',
            name='gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='pin_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
