# Generated by Django 5.0.6 on 2024-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_inquiry_subscriber_alter_house_pin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(choices=[('Availability', 'Availability'), ('Charges', 'Charges'), ('Others', 'Others')], default='null', max_length=15),
            preserve_default=False,
        ),
    ]
